# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_prefs\RnD\maya\python\Export\pw_MayaToHoudiniChannelExport\widgets\channelExportWindow.ui'
#
# Created: Sat Jul 19 14:46:13 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_channelExportWindow(object):
    def setupUi(self, channelExportWindow):
        channelExportWindow.setObjectName("channelExportWindow")
        channelExportWindow.resize(432, 621)
        self.centralwidget = QtGui.QWidget(channelExportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tree_ly = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.tree_ly.setContentsMargins(0, 0, 0, 0)
        self.tree_ly.setObjectName("tree_ly")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addSelectedObject_btn = QtGui.QPushButton(self.groupBox)
        self.addSelectedObject_btn.setObjectName("addSelectedObject_btn")
        self.verticalLayout.addWidget(self.addSelectedObject_btn)
        self.addFromChannelBox_btn = QtGui.QPushButton(self.groupBox)
        self.addFromChannelBox_btn.setObjectName("addFromChannelBox_btn")
        self.verticalLayout.addWidget(self.addFromChannelBox_btn)
        self.addFromSet_btn = QtGui.QPushButton(self.groupBox)
        self.addFromSet_btn.setObjectName("addFromSet_btn")
        self.verticalLayout.addWidget(self.addFromSet_btn)
        self.addFromFile_btn = QtGui.QPushButton(self.groupBox)
        self.addFromFile_btn.setObjectName("addFromFile_btn")
        self.verticalLayout.addWidget(self.addFromFile_btn)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.saveToSet_btn = QtGui.QPushButton(self.groupBox_3)
        self.saveToSet_btn.setObjectName("saveToSet_btn")
        self.verticalLayout_5.addWidget(self.saveToSet_btn)
        self.saveToFile_btn = QtGui.QPushButton(self.groupBox_3)
        self.saveToFile_btn.setObjectName("saveToFile_btn")
        self.verticalLayout_5.addWidget(self.saveToFile_btn)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.removeSelected_btn = QtGui.QPushButton(self.groupBox_2)
        self.removeSelected_btn.setObjectName("removeSelected_btn")
        self.verticalLayout_2.addWidget(self.removeSelected_btn)
        self.removeNonExists_btn = QtGui.QPushButton(self.groupBox_2)
        self.removeNonExists_btn.setObjectName("removeNonExists_btn")
        self.verticalLayout_2.addWidget(self.removeNonExists_btn)
        self.removeAll_btn = QtGui.QPushButton(self.groupBox_2)
        self.removeAll_btn.setObjectName("removeAll_btn")
        self.verticalLayout_2.addWidget(self.removeAll_btn)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.info_lb = QtGui.QLabel(self.layoutWidget)
        self.info_lb.setObjectName("info_lb")
        self.verticalLayout_3.addWidget(self.info_lb)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.splitter)
        self.outFile_ly = QtGui.QHBoxLayout()
        self.outFile_ly.setObjectName("outFile_ly")
        self.verticalLayout_4.addLayout(self.outFile_ly)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scale_ly = QtGui.QHBoxLayout()
        self.scale_ly.setObjectName("scale_ly")
        self.gridLayout_2.addLayout(self.scale_ly, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setContentsMargins(4, 5, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.endRange_spb = QtGui.QSpinBox(self.groupBox_4)
        self.endRange_spb.setMinimum(-999999999)
        self.endRange_spb.setMaximum(999999999)
        self.endRange_spb.setObjectName("endRange_spb")
        self.gridLayout.addWidget(self.endRange_spb, 0, 3, 1, 1)
        self.startRange_spb = QtGui.QSpinBox(self.groupBox_4)
        self.startRange_spb.setMinimum(-999999999)
        self.startRange_spb.setMaximum(999999999)
        self.startRange_spb.setObjectName("startRange_spb")
        self.gridLayout.addWidget(self.startRange_spb, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.autoRange_cbx = QtGui.QCheckBox(self.groupBox_4)
        self.autoRange_cbx.setObjectName("autoRange_cbx")
        self.gridLayout.addWidget(self.autoRange_cbx, 1, 0, 2, 1)
        self.currentTimeToStart_btn = QtGui.QPushButton(self.groupBox_4)
        self.currentTimeToStart_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.currentTimeToStart_btn.setObjectName("currentTimeToStart_btn")
        self.gridLayout.addWidget(self.currentTimeToStart_btn, 0, 1, 1, 1)
        self.currentTimeToEnd_btn = QtGui.QPushButton(self.groupBox_4)
        self.currentTimeToEnd_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.currentTimeToEnd_btn.setObjectName("currentTimeToEnd_btn")
        self.gridLayout.addWidget(self.currentTimeToEnd_btn, 0, 4, 1, 1)
        self.setTimeLineRange_btn = QtGui.QPushButton(self.groupBox_4)
        self.setTimeLineRange_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.setTimeLineRange_btn.setObjectName("setTimeLineRange_btn")
        self.gridLayout.addWidget(self.setTimeLineRange_btn, 2, 1, 1, 4)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.batchMode_btn = QtGui.QPushButton(self.centralwidget)
        self.batchMode_btn.setMinimumSize(QtCore.QSize(40, 30))
        self.batchMode_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.batchMode_btn.setObjectName("batchMode_btn")
        self.horizontalLayout.addWidget(self.batchMode_btn)
        self.export_btn = QtGui.QPushButton(self.centralwidget)
        self.export_btn.setMinimumSize(QtCore.QSize(40, 30))
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout.addWidget(self.export_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.progress_pbr = QtGui.QProgressBar(self.centralwidget)
        self.progress_pbr.setProperty("value", 0)
        self.progress_pbr.setObjectName("progress_pbr")
        self.verticalLayout_4.addWidget(self.progress_pbr)
        self.verticalLayout_4.setStretch(0, 1)
        channelExportWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(channelExportWindow)
        QtCore.QObject.connect(self.autoRange_cbx, QtCore.SIGNAL("toggled(bool)"), self.startRange_spb.setDisabled)
        QtCore.QObject.connect(self.autoRange_cbx, QtCore.SIGNAL("toggled(bool)"), self.endRange_spb.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(channelExportWindow)

    def retranslateUi(self, channelExportWindow):
        channelExportWindow.setWindowTitle(QtGui.QApplication.translate("channelExportWindow", "Maya to Houdini channel exporter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("channelExportWindow", "Add channel", None, QtGui.QApplication.UnicodeUTF8))
        self.addSelectedObject_btn.setText(QtGui.QApplication.translate("channelExportWindow", "Selected objects", None, QtGui.QApplication.UnicodeUTF8))
        self.addFromChannelBox_btn.setText(QtGui.QApplication.translate("channelExportWindow", "From Channel Box", None, QtGui.QApplication.UnicodeUTF8))
        self.addFromSet_btn.setText(QtGui.QApplication.translate("channelExportWindow", "From Set", None, QtGui.QApplication.UnicodeUTF8))
        self.addFromFile_btn.setText(QtGui.QApplication.translate("channelExportWindow", "Import From File", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("channelExportWindow", "Save channels", None, QtGui.QApplication.UnicodeUTF8))
        self.saveToSet_btn.setText(QtGui.QApplication.translate("channelExportWindow", "Save To Set", None, QtGui.QApplication.UnicodeUTF8))
        self.saveToFile_btn.setText(QtGui.QApplication.translate("channelExportWindow", "Export To File", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("channelExportWindow", "Remove channel", None, QtGui.QApplication.UnicodeUTF8))
        self.removeSelected_btn.setText(QtGui.QApplication.translate("channelExportWindow", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.removeNonExists_btn.setText(QtGui.QApplication.translate("channelExportWindow", "Remove Nonexistent Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.removeAll_btn.setText(QtGui.QApplication.translate("channelExportWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.info_lb.setText(QtGui.QApplication.translate("channelExportWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("channelExportWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("channelExportWindow", "Frame Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("channelExportWindow", "Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.autoRange_cbx.setToolTip(QtGui.QApplication.translate("channelExportWindow", "<html><head/><body><p>Request range from all animation curves in scene and set maximum and minimum to range </p><p>Always On in batch mode</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.autoRange_cbx.setText(QtGui.QApplication.translate("channelExportWindow", "AUTO", None, QtGui.QApplication.UnicodeUTF8))
        self.currentTimeToStart_btn.setText(QtGui.QApplication.translate("channelExportWindow", "►", None, QtGui.QApplication.UnicodeUTF8))
        self.currentTimeToEnd_btn.setText(QtGui.QApplication.translate("channelExportWindow", "◄", None, QtGui.QApplication.UnicodeUTF8))
        self.setTimeLineRange_btn.setText(QtGui.QApplication.translate("channelExportWindow", "▲     From Time Line    ▲ ", None, QtGui.QApplication.UnicodeUTF8))
        self.batchMode_btn.setToolTip(QtGui.QApplication.translate("channelExportWindow", "<html><head/><body><p>1. Open rig scene</p><p>2. Load objects to list</p><p>3. Press Batch ...</p><p>4. Select fbx files</p><p><br/></p><p>Auto will be turn ON</p><p>Out clip file path will same as fbx file path</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.batchMode_btn.setText(QtGui.QApplication.translate("channelExportWindow", "Batch...", None, QtGui.QApplication.UnicodeUTF8))
        self.export_btn.setText(QtGui.QApplication.translate("channelExportWindow", "EXPORT", None, QtGui.QApplication.UnicodeUTF8))

